---
title: "Exploratory Data Analysis"
author: "Critical Thinking Group 3"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: kate
    toc_depth: 3
    code_folding: "hide"
---

```{r knitr_init, echo=FALSE, cache=FALSE, message=FALSE}
library(knitr)
library(rmdformats)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(gridExtra)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r read_data}
training <- read.csv("../data/moneyball-training-data.csv")
```

## Exploration

### Summary Statistics

The following is a summary of the data.

```{r}
training %>% 
  select(-INDEX) %>%
  summary(.) %>%
  kable() %>%
  kable_styling()
```

### Plots

The following density plots show the spread of the data.  The red verticle line is the mean and the blue verticle line is the median.  The scatter plot shows the relationship between wins and the variable

```{r}
plot_me <- function(d, title, xlab, ylab){
  nas <- d %>% filter(is.na(x)) %>% nrow()
  density <- d %>%
    filter(!is.na(x)) %>%
    ggplot(., aes(x, stat(count))) +
    geom_density() +
    labs(title = title, 
       x = xlab,
       y = ylab) +
    theme(panel.background = element_blank(),
        panel.grid.major = element_line(color = "gray95")) +
    geom_vline(xintercept = mean(d$x, na.rm = TRUE), color = "red") +
    geom_vline(xintercept = median(d$x, na.rm = TRUE), color = "blue")
  # Add annotation for NA's
  if(nas > 0){
    density <- density + ggtitle(title, subtitle = paste(nas, "Null Observations")) 
  }
  
  # Create a scatter plot
  scatter <- ggplot(d, aes(x, TARGET_WINS)) +
    geom_point() + 
    geom_smooth(method = lm) + 
    labs(x = xlab,
         y = ylab) +
    expand_limits(y=0) +
    theme(panel.background = element_blank(),
          panel.grid.major = element_line(color = "gray95"))
  # Put them side by side
  grid.arrange(density, scatter, ncol=2)
}
```

```{r}
training %>%
  mutate(x = TARGET_WINS) %>%
  plot_me(., "Wins", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_H) %>%
  plot_me(., "Base Hits", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_2B) %>%
  plot_me(., "Doubles", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_3B) %>%
  plot_me(., "Triples", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_HR) %>%
  plot_me(., "Homeruns", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_BB) %>%
  plot_me(., "Walks", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_HBP) %>%
  plot_me(., "Batters Hit by Pitch", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BATTING_SO) %>%
  plot_me(., "Strikeouts", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BASERUN_SB) %>%
  plot_me(., "Stolen Bases", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_BASERUN_CS) %>%
  plot_me(., "Caught Stealing Bases", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_FIELDING_E) %>%
  plot_me(., "Errors", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_FIELDING_DP) %>%
  plot_me(., "Double Plays", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_PITCHING_BB) %>%
  plot_me(., "Walks Allowed", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_PITCHING_H) %>%
  plot_me(., "Hits Allowed", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_PITCHING_HR) %>%
  plot_me(., "Homeruns Allowed", element_blank(), element_blank())
```

```{r}
training %>%
  mutate(x = TEAM_PITCHING_SO) %>%
  plot_me(., "Strikouts by Pitcher", element_blank(), element_blank())
```
